issue-4: Implemented the class diagram in the UML model for Java
andrejnascimento/api_purchase_order pull request #5
Opened 2024-08-16 19:14 UTC by andrejnascimento

- Created the **CreditCard**  class
- Created the **DebitCard** class 
- Created the **PaymentType**  Interface returning **PaymentStatus** Class

2024-08-19 21:02 UTC, apiresmaster requested changes

2024-08-19 21:02 UTC, apiresmaster commented on README.md
> +```mermaid
Acho que podemos mover esse arquivo para outro PR, pois esse é referente a issuer-4 que trata da implementação do diagrama de classes, já o README.md é referente aquela task do board antigo, que estava na minha conta.

2024-08-19 21:02 UTC, apiresmaster commented on README.md
> +```mermaid
o que acha de:
 - Criar uma outra issuer para o README.md
 - Abrir outro PR com somente esse arquivo?
 
 ai ficamos com 2s PR cada um com sua responsabilidade?

2024-08-20 23:01 UTC, andrejnascimento commented on README.md
> +```mermaid
Pronto!
- Issuer para o README.md foi criada.
- PR aberta para a modificação.

2024-08-21 21:50 UTC, apiresmaster reviewed
@andrejnascimento deixei uns comments para sua avaliação. Bom trabalho.

2024-08-21 21:50 UTC, apiresmaster commented on README.md
> +```mermaid
Fazer um `git rebase develop`, pois já existe na branch de develop

2024-08-21 21:50 UTC, apiresmaster commented on src/main/java/models/CreditCard.java
> +    public PaymentStatus checkStatus(String amount) {
Vale trocar o nome do argumento de `amount` para `name` ou `statusName`??

2024-08-21 21:50 UTC, apiresmaster commented on src/main/java/models/DebitCard.java
> +    public PaymentStatus checkStatus(String amount) {
Idem ao comentário anterior.

2024-08-21 21:50 UTC, apiresmaster commented on src/main/java/models/PaymentType.java
> +   public PaymentStatus checkStatus(String hash);
Idem ao comentário anterior.

2024-08-30 12:13 UTC, apiresmaster approved these changes
Show de bola brother, não esquece de na hora de completar o PR usar a opção `squash and merge`ou `rebase and merge`

2024-09-02 13:34 UTC, merged